# Generated by Django 5.0.8 on 2024-08-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Auth', '0032_merge_20240821_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_wishes', to='User_Auth.user')),
                ('userwish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishes', to='User_Auth.user')),
            ],
        ),
    ]
