# Generated by Django 5.0.8 on 2024-08-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_wish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwish',
            name='tag',
        ),
    ]
