# Generated by Django 5.0.8 on 2024-08-22 07:57
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_wish', '0002_remove_userwish_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.utcnow()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.utcnow()),
        ),
    ]
