# Generated by Django 5.0.8 on 2024-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wish', '0003_userwish_created_at_userwish_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
