# Generated by Django 5.0.8 on 2024-09-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wish', '0004_alter_userwish_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userwish',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
