# Generated by Django 5.0.8 on 2024-09-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_wish', '0005_userwish_is_active_userwish_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwish',
            name='reminder_date',
        ),
    ]
