# Generated by Django 5.0.8 on 2024-08-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0032_merge_20240821_1214'),
        ('user_connection', '0002_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to', to='User_Auth.user')),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from', to='User_Auth.user')),
            ],
            options={
                'unique_together': {('reporter_id', 'reported_id')},
            },
        ),
    ]
