# Generated by Django 5.0.8 on 2024-08-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0032_merge_20240821_1214'),
        ('user_connection', '0003_reporteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteduser',
            name='reported_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_to', to='User_Auth.user'),
        ),
        migrations.AlterField(
            model_name='reporteduser',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='User_Auth.user'),
        ),
    ]
