# Generated by Django 5.0.8 on 2024-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection', '0004_alter_reporteduser_reported_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
