# Generated by Django 5.0.8 on 2024-08-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
