# Generated by Django 5.0.7 on 2024-08-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_security_q',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('security_q', models.CharField(max_length=200)),
                ('security_a', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_security', to='User_Auth.user')),
            ],
        ),
    ]
