# Generated by Django 5.0.8 on 2024-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_user_dob_user_first_name_user_gender_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
