# Generated by Django 5.0.8 on 2024-08-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
