# Generated by Django 5.0.7 on 2024-08-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0003_usersecurityquestion_delete_u_security_q'),
        ('User_Auth', '0008_rename_dob_user_dob'),
    ]

    operations = [
    ]
