# Generated by Django 5.0.7 on 2024-08-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0010_alter_user_first_name_alter_user_gender_and_more'),
        ('User_Auth', '0010_alter_user_last_name'),
    ]

    operations = [
    ]
