# Generated by Django 5.0.8 on 2024-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0009_alter_user_first_name_alter_user_last_name'),
        ('User_Auth', '0013_alter_user_dob'),
    ]

    operations = [
    ]
