# Generated by Django 5.0.8 on 2024-08-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0014_merge_20240813_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
    ]
