# Generated by Django 5.0.7 on 2024-08-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0011_alter_usersecurityquestion_security_q'),
        ('User_Auth', '0011_merge_20240813_1633'),
        ('User_Auth', '0015_alter_user_dob'),
    ]

    operations = [
    ]
