# Generated by Django 5.0.8 on 2024-08-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0014_alter_user_dob'),
        ('User_Auth', '0015_alter_user_dob'),
    ]

    operations = [
    ]
