# Generated by Django 5.0.7 on 2024-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0016_merge_20240814_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
