# Generated by Django 5.0.7 on 2024-08-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0029_alter_user_phone_no'),
        ('User_Auth', '0029_merge_0017_alter_user_dob_0028_alter_user_dob'),
    ]

    operations = [
    ]
