# Generated by Django 5.0.8 on 2024-08-21 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('User_Auth', '0002_user_dob_user_first_name_user_gender_user_last_name_and_more'),
        ('User_Auth', '0029_merge_0017_alter_user_dob_0028_alter_user_dob'),
        ('User_Auth', '0031_alter_user_phone_no'),
    ]

    operations = [
    ]

