# Generated by Django 5.0.8 on 2024-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0033_user_is_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_block',
        ),
    ]
