# Generated by Django 5.0.8 on 2024-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0035_user_is_block_alter_user_dob_alter_user_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_block',
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
